#!/usr/bin/env bash

export CONTECO_LABEL="Image Wrapper"
export CONTECO_DESCRIPTION="The conteco.image.wrapper image implements the functionality common to all ContEco containers."

export CONTECO_TYPE="image"
export CONTECO_NAME="wrapper"
export CONTECO_TAG="v1.1.6"

export CONTECO_BASE="external.bash"
export CONTECO_BUILD="image-wrapper"
