---
version: '3'
services:

# START SERVICE image.wrapper
  image:
    image: ${CONTECO_REGISTRY}${CONTECO_REALM_RUNTIME}/conteco.${CONTECO_DC_GLOBAL_IMAGE_NAME}
    environment: []
    command: ['sleep 0.5']
    volumes: []
    ports: []
    networks: []
    deploy:
      mode: replicated
      resources:
        limits:
          memory: '128m'
        reservations:
          memory: '5m'
${CONTECO_DC_IMAGE_WRAPPER_COMPOSE_EXTENSIONS}
# END SERVICE image.wrapper

networks: {${CONTECO_DC_GLOBAL_NETWORKS}}
volumes: {${CONTECO_DC_GLOBAL_VOLUMES}}
${CONTECO_DC_GLOBAL_COMPOSE_EXTENSIONS}
