---
version: '3'
services:

# START SERVICE image.wrapper
  image:
    image: ${CONTECO_REGISTRY}${CONTECO_REALM_RUNTIME}/conteco.${CONTECO_DC_GLOBAL_IMAGE_NAME}
    environment: []
    command: ['sleep 0.5']
    volumes: []
    ports: []
    networks: []
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: ''
          memory: '128m'
        reservations:
          cpus: '0.0'
          memory: '5m'
      placement:
        constraints: []
      labels: []
    labels: []
# END SERVICE image.wrapper

volumes: {${CONTECO_DC_GLOBAL_VOLUMES}}
networks: {${CONTECO_DC_GLOBAL_NETWORKS}}
