---
version: '3'
services:

# START SERVICE image.wrapper
  image:
    image: ${CONTECO_REGISTRY}${CONTECO_REALM_RUNTIME}/conteco.${CONTECO_DC_GLOBAL_IMAGE_NAME}
    environment: []
    command: ['sleep 0.5']
    volumes: []
    ports: []
    networks: []
    deploy:
      mode: replicated
      resources:
        limits:
          cpus: ''
          memory: '128m'
        reservations:
          cpus: ''
          memory: '5m'
      placement:
        constraints: []
      ${CONTECO_DC_BASH_DEPLOY_EXTENSIONS}
    ${CONTECO_DC_BASH_SERVICE_EXTENSIONS}
# END SERVICE image.wrapper

networks: {${CONTECO_DC_GLOBAL_NETWORKS}}
volumes: {${CONTECO_DC_GLOBAL_VOLUMES}}
${CONTECO_DC_BASH_GLOBAL_EXTENSIONS}
