---
version: '3'
services:

# START SERVICE image.wrapper
  image:
    image: ${CONTECO_REGISTRY}${CONTECO_REALM_RUNTIME}/conteco.${CONTECO_DC_GLOBAL_IMAGE_NAME}
    environment: []
    command: ['usleep 500000000']
    volumes: []
    ports: []
    networks: []
    deploy:
      mode: replicated
      resources:
        limits:
          cpus: '0.75'
          memory: '128m'
        reservations:
          cpus: '0.0'
          memory: '5m'
      labels: [${CONTECO_DC_IMAGE_WRAPPER_DEPLOY_LABELS}]
# END SERVICE image.wrapper

volumes: {${CONTECO_DC_GLOBAL_VOLUMES}}
networks: {${CONTECO_DC_GLOBAL_NETWORKS}}
