#!/usr/bin/env bash
(
    . executionplane-invoke "$0 $@"
	if [[ "$1" == "all" ]] ; then
		shift
	fi
    config $@
#    executionplane-info "Image does not implement config."
    executionplane-complete
)