#!/usr/bin/env bash
(
    . executionplane-invoke "$0 $@"
	if [[ "$1" == "all" ]] ; then
		shift
	fi
#    deploy $@
    executionplane-info "Image does not implement deploy."
    executionplane-complete
)
