#!/usr/bin/env bash
(
    . executionplane-invoke "$0 $@"
	if [[ "$1" == "all" ]] ; then
		shift
	fi
    . executionplane-error "No image specific implementation for release."
    executionplane-complete
)
